config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :palaces do

    resources :bookings, only: [:new, :create, :show, :update, :edit]
  end

  get "/dashboard/palaces", to: "pages#palaces"
  get "/dashboard/bookings_as_visitor", to: "pages#bookings_as_visitor"
  get "/dashboard/bookings_as_owner", to: "pages#bookings_as_owner"
  #   resources :bookings, only: [:update, :edit, :show, :index, :cancel]

  resources :bookings, only: [:update, :edit, :show, :index] do
    member do
      patch "/accept", to: "bookings#accept"
      patch "/refuse", to: "bookings#refuse"
    end
  end

  get "/dashboard/profil", to: "pages#profil"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :palace

  validates :begin_date, :end_date, presence: true
end

app/models/palace.rb
class Palace < ApplicationRecord
  include PgSearch::Model
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :name, :description, :address, presence: true
  validates :description, length: { minimum: 12 }

  pg_search_scope :search_by_location,
                  against: [:address],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :palaces, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_many :bookings_as_visitor, class_name: "Booking", dependent: :destroy
  has_many :bookings_as_owner, through: :palaces, source: :bookings

  has_one_attached :photo

  validates :first_name, presence: true, uniqueness: { scope: :last_name }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
 class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :update, :edit]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
  end

  def new
    @palace = Palace.find(params[:palace_id])
    @booking = Booking.new
  end

  def create

    @palace = Palace.find(params[:palace_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.status = nil
    @booking.palace = @palace

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @booking.status = nil
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: 'Booking updated successfully!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def accept
    puts "on est entré dans accept"
    @booking = Booking.find(params[:id])
    puts "l'ID du booking est #{@booking.id}"
    if @booking.update(status: true)
      redirect_to booking_path(@booking)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def refuse
    @booking = Booking.find(params[:id])

    if @booking.update(status: false)
      redirect_to booking_path(@booking)
    else
      render :show, status: :unprocessable_entity
    end
  end

#   def cancel
#     @booking.status = false
#     @booking.save!
#     redirect_to bookings_path
#   end

  private
  def booking_params
    params.require(:booking).permit(:begin_date, :end_date, :palace_id, :booking_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :profil]

  def home
    if params[:query].present?
      @palaces = Palace.search_by_location(params[:query])
    else
      @palaces = Palace.all
    end
  end

  def palaces
    @palaces = Palace.where(user_id: current_user.id)
  end

  def bookings_as_visitor
    @past_bookings = current_user.bookings_as_visitor.where("end_date < ?", Date.current)
    @future_bookings = current_user.bookings_as_visitor.where("begin_date > ?", Date.current)
    @cancelled_bookings = current_user.bookings_as_visitor.where(status: false)
  end

  def bookings_as_owner
    @manager_past_bookings = current_user.bookings_as_owner.where("end_date < ?", Date.current)
    @manager_future_bookings = current_user.bookings_as_owner.where("begin_date > ?", Date.current)
    @manager_cancelled_bookings = current_user.bookings_as_owner.where(status: false)
  end

  def profil
    @user = current_user
  end

  # def mybookings
  #   @mybookings =
  # end
end

app/controllers/palaces_controller.rb
class PalacesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  before_action :set_palace, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @palaces = Palace.search_by_location(params[:query])
    else
      @palaces = Palace.all
    end
  end

  def show
    @palace = Palace.find(params[:id])
    @booking = Booking.new

    if @palace.geocoded?
      @marker = {
        lat: @palace.latitude,
        lng: @palace.longitude,
        marker_html: render_to_string(partial: "marker")
      }
    end
    puts "le marker doit etre"
    puts @marker
  end

  def new
    @palace = Palace.new
  end

  def create
    @palace = Palace.new(palace_params)
    @palace.user = current_user
    if @palace.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
   if @palace.update(palace_params)
    redirect_to palace_path(@palace)
   else
    render :edit, status: :unprocessable_entity
   end
  end

  def destroy
   if @palace.destroy
    redirect_to palaces_path
   else
    render :new, status: :unprocessable_entity
   end
  end

  private

  def palace_params
    params.require(:palace).permit(:name, :description, :address, :price, photos: [])
  end

  def set_palace
    @palace = Palace.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
    <div class="col">
      <p class="text-center"><strong>Book the palace!</strong></p>
      <p class = 'text-align'><%= @palace.price %>€ / nuit</p>
      <%= simple_form_for [@palace, @booking],
        html: {data: { controller: 'flatpickr' } } do |f| %>
        <%= f.input :begin_date, as: :string, input_html: { data: { flatpickr_target: 'startDateInput', } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: 'endDateInput' } } %>
        <%= f.submit "Send the booking request!", class: "btn btn-primary" %>
      <% end %>
    </div>
  <%# <div><%= link_to "Back", palace_path(@palace), class: "btn btn-ghost"%>
</div>

app/views/bookings/show.html.erb
<div class="container-fluid" style="padding: 0;">
  <div class="image-container" style="width: 100%; height: 300px; background-image: url('https://www.yonder.fr/sites/default/files/styles/lg-insert/public/contenu/destinations/Tiara%20Yaktsa.jpg?itok=Y9VNk2pA'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="d-flex justify-content-center align-items-center h-100" style="background: rgba(0, 0, 0, 0.5);">
      <h2 style="color:hsl(0, 0.00%, 100.00%); font-family: 'Arial', sans-serif; font-size: 26px; text-align: center; text-transform: uppercase; letter-spacing: 2px; padding-bottom: 10px;">
      My booking details</h2>
    </div>
  </div>


  <div class="container mt-5 d-flex justify-content-center">
    <div class = "card border-0 rounded shadow-lg p-4" style="max-width: 700px; width: 100%;">
      <div class="form-group mb-3">
        <h2 class="display-5" style="color:rgb(86, 87, 87); font-family: 'Arial', sans-serif; text-align: center; font-size: 2.5rem;border-bottom: 1px solid rgb(221, 219, 219); padding-bottom: 10px;">
        <%= @booking.palace.name %></h2>
      </div>

      <div class="form-group mb-3">
        <h4 style="color:rgb(86, 87, 87); font-family: 'Arial', sans-serif;">Booking Period</h4>
        <p><strong>Start:</strong> <%= @booking.begin_date.strftime("%-d %B %Y") %></p>
        <p><strong>End:</strong> <%= @booking.end_date.strftime("%-d %B %Y") %></p>
      </div>

      <div class="form-group mb-3">
        <h4 style="color:rgb(86, 87, 87); font-family: 'Arial', sans-serif;">Booked by</h4>
        <p><%= @booking.user.email %></p>
      </div>

      <div class="form-group mb-3">
        <h4 style="color:rgb(86, 87, 87)" style="font-family: 'Arial', sans-serif;">Palace Details</h4>
        <p><strong>Name:</strong> <%= @booking.palace.name %></p>
        <p><strong>Address:</strong> <%= @booking.palace.address %></p>
        <p><strong>Description:</strong> <%= @booking.palace.description %></p>
        <p><strong>Price:</strong> <%= @booking.palace.price %>€ par nuit</p>
      </div>


      <div class="form-group mb-3">
        <h4 style="color:rgb(86, 87, 87)" style="font-family: 'Arial', sans-serif;">Status</h4>
        <% if @booking.status.nil? %>
          <p>To be confirmed</p>
        <% elsif @booking.status == false %>
          <p class="text-danger">Refused</p>
        <% else %>
          <p class="text-success">Confirmed</p>
        <% end %>
      </div>

      <div class="d-flex justify-content-between">
          <% if @booking.user == current_user %>
            <%= link_to "Edit the booking", edit_booking_path(@booking), class: "button-card" %>
          <% elsif current_user == @booking.palace.user %>
            <% if @booking.status.nil? %>
              <%= link_to "Accept the booking", accept_booking_path(@booking), class: "button-search", data: { turbo_method: :patch } %>
              <%= link_to "Refuse the booking", refuse_booking_path(@booking), class: "button-card", data: { turbo_method: :patch } %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/pages/bookings_as_owner.html.erb
<div class="container mt-5">

<div class= "row">
  <ul class="nav nav-tabs" >
    <div class= "col-4">
      <li class="nav-item flex-fill">
        <%= link_to dashboard_palaces_path, class: "nav-link w-100" do %>
            <div aria-current="page">SEE MY PALACES</div>
        <% end %>
      </li>
      </div>
      <div class = "col-4">
      <li class="nav-item flex-fill">
        <%= link_to dashboard_bookings_as_owner_path, class: "nav-link active w-100" do %>
            <div aria-current="page", >MANAGE THE BOOKING</div>
        <% end %>
      </li>
        </div>
        <div class= "col-4">
      <li class="nav-item flex-fill">
        <%= link_to new_palace_path, class: "nav-link w-100" do %>
        <div aria-current="page", >ADD A PALACE</div>
        <% end %>
      </li>
    </div>
  </ul>
</div>
 <div class="container mt-5">
  <div class="my-5">
    <h2 style="color: #6c757d; font-family: 'Arial', sans-serif; font-size: 26px; text-align: center; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #6c757d; padding-bottom: 10px;">
      Manage My Future Bookings
    </h2>
    <div class="row gx-4">
      <% if @manager_future_bookings.empty? %>
        <div class="card" style="color: #6c757d; width: 15rem; margin: auto; height: 16rem; overflow: hidden; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
          <div class="card-body" style="padding: 1rem;">
             <h5 class="card-title" style="color: #6c757d; font-size: 1rem; margin-bottom: 0.25rem;text-align: center;">No booking here yet!</h5>
          </div>
        </div>
      <% else %>
        <% @manager_future_bookings.each do |booking| %>
          <div class="col-6 col-md-3" style="margin-bottom: 1.5rem;">
            <%= link_to booking_path(booking), class: "card-link" do %>

              <div class="card" style="width: 12rem; margin: auto; height: 18rem; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
                <div id="carousel<%= dom_id(booking.palace) %>" class="carousel slide">
                  <div class="carousel-inner">
                    <% if booking.palace.photos.any? %>
                      <% booking.palace.photos.each do |photo| %>
                        <div class="carousel-item active">
                        <%= cl_image_tag photo.key, class:"d-block w-100 card-img-top", style:"object-fit: cover; height: 6rem; width: 100%;", alt:"Image of #{booking.palace.name}" %>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="carousel-item">
                        <img src="https://cdn.lecollectionist.com/__lecollectionist__/production/houses/7336/photos/Yz13vnLwSjG3i5F4VdpC_0c03f529-5d68-40c4-b964-c19b8d16c019.jpg?width=2880&q=65"
                        class="card-img-top" style="object-fit: cover; height: 6rem; width: 100%;" alt="Image of <%= booking.palace.name %>">
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= dom_id(booking.palace) %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= dom_id(booking.palace) %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>

                <div class="card-body" style="padding: 1rem;">
                  <h5 class="card-title card-title card-title-test" style="color: #6c757d; font-size: 1rem;"><strong><%= booking.palace.name %></strong></h5>
                  <p class="card-text" style="font-size: 0.75rem; margin-bottom: 0.5rem;">Visitor: <%= booking.user.first_name %></p>
                  <p class="card-text" style="font-size: 0.75rem;">Start Date: <%= booking.begin_date.strftime("%-d %B %Y") %></p>
                  <p class="card-text" style="font-size: 0.75rem;">End Date: <%= booking.end_date.strftime("%-d %B %Y") %></p>
                  <% if booking.status.nil? %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Pending</p>
                  <% elsif booking.status == true %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Confirmed</p>
                  <% else %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Denied</p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <!-- Historique des réservations passées -->
  <div class="my-5">
    <h2 style="color: #6c757d; font-family: 'Arial', sans-serif; font-size: 26px; text-align: center; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #6c757d; padding-bottom: 10px;">
      History of Past Bookings
    </h2>
    <div class="row gx-4">
      <% if @manager_past_bookings.empty? %>
       <div class="card" style="width: 12rem; margin: auto; height: 18rem; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
      <div class="card-body d-flex justify-content-center" style="padding: 0.75rem;">
        <h5 class="card-title" style="color: #6c757d; font-size: 1rem; margin-bottom: 0.25rem;text-align: center;">No booking here yet!</h5>
      </div>
    </div>
      <% else %>
        <% @manager_past_bookings.each do |booking| %>
          <div class="col-6 col-md-3" style="margin-bottom: 1.5rem;">
            <%= link_to booking_path(booking), class: "card-link" do %>
              <div class="card" style="width: 12rem; margin: auto; height: 18rem; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
                <div class="card-body" style="padding: 1rem;">
                  <h5 class="card-title" style="font-size: 1rem;"><strong><%= booking.palace.name %></strong></h5>
                  <p class="card-text" style="font-size: 0.75rem; margin-bottom: 0.5rem;">Visitor: <%= booking.user.first_name %></p>
                  <p class="card-text" style="font-size: 0.75rem;">Start Date: <%= booking.begin_date.strftime("%-d %B %Y") %></p>
                  <p class="card-text" style="font-size: 0.75rem;">End Date: <%= booking.end_date.strftime("%-d %B %Y") %></p>
                  <% if booking.status.nil? %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Pending</p>
                  <% elsif booking.status == true %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Confirmed</p>
                  <% else %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Denied</p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <!-- Historique des réservations annulées -->
  <div class="my-5">
    <h2 style="color: #6c757d; font-family: 'Arial', sans-serif; font-size: 26px; text-align: center; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #6c757d; padding-bottom: 10px;">
      History of Canceled Bookings
    </h2>
    <div class="row gx-4">
      <% if @manager_cancelled_bookings.empty? %>
        <div class="card" style="width: 12rem; margin: auto; height: 18rem; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
      <div class="card-body d-flex justify-content-center" style="padding: 0.75rem;">
        <h5 class="card-title" style="color: #6c757d; font-size: 1rem; margin-bottom: 0.25rem;text-align: center;">No booking here yet!</h5>
      </div>
    </div>
      <% else %>
        <% @manager_cancelled_bookings.each do |booking| %>
          <div class="col-6 col-md-3" style="margin-bottom: 1.5rem;">
            <%= link_to booking_path(booking), class: "card-link" do %>
              <div class="card" style="width: 12rem; margin: auto; height: 18rem; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease-in-out;">
                <div class="card-body" style="padding: 1rem;">
                  <h5 class="card-title" style="font-size: 1rem;"><strong><%= booking.palace.name %></strong></h5>
                  <p class="card-text" style="font-size: 0.75rem; margin-bottom: 0.5rem;">Visitor: <%= booking.user.first_name %></p>
                  <p class="card-text" style="font-size: 0.75rem;">Start Date: <%= booking.begin_date.strftime("%-d %B %Y") %></p>
                  <p class="card-text" style="font-size: 0.75rem;">End Date: <%= booking.end_date.strftime("%-d %B %Y") %></p>
                  <% if booking.status.nil? %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Pending</p>
                  <% elsif booking.status == true %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Confirmed</p>
                  <% else %>
                    <p class="card-text" style="font-size: 0.75rem;">Status: Denied</p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/pages/palaces.html.erb
<div class="container mt-5">
<div class= "row">
    <ul class="nav nav-tabs" >
      <div class= "col-4">
      <li class="nav-item flex-fill">
        <%= link_to dashboard_palaces_path, class: "nav-link active w-100" do %>
            <div aria-current="page">SEE MY PALACES</div>
        <% end %>
      </li>
      </div>
      <div class = "col-4">
      <li class="nav-item flex-fill">
        <%= link_to dashboard_bookings_as_owner_path, class: "nav-link w-100" do %>
            <div aria-current="page", >MANAGE THE BOOKING</div>
        <% end %>
        </li>
        </div>
        <div class= "col-4">
      <li class="nav-item flex-fill">
        <%= link_to new_palace_path, class: "nav-link w-100" do %>
        <div aria-current="page", >ADD A PALACE</div>
      <% end %>
      </li>
        </div>
      </ul>
      </div>

      <div class="container mt-5">
        <div class="row justify-content-evenly g-3">
          <% @palaces.each do |palace| %>
            <div class="card rounded shadow-lg" style="width: 18rem;">
              <div id="carousel<%= dom_id(palace) %>" class="carousel slide">
              <div class="carousel-inner">
                <% if palace.photos.any? %>
                  <% palace.photos.each do |photo| %>
                    <div class="carousel-item active card-img-top" style="object-fit: contain;" alt="...">
                    <%= cl_image_tag photo.key, class:"d-block w-100" %>
                  </div>
                  <% end %>
                <% else %>
                  <div class="carousel-item">
                  <img src="https://cdn.lecollectionist.com/__lecollectionist__/production/houses/7336/photos/Yz13vnLwSjG3i5F4VdpC_0c03f529-5d68-40c4-b964-c19b8d16c019.jpg?width=2880&q=65" class="card-img-top" style="object-fit: contain;" alt="...">
                  </div>
                <% end %>
              </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= dom_id(palace) %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= dom_id(palace) %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>

        <div class="card-body">
          <h5 class="card-title card-title-test"><strong><%= palace.name %></strong></h5>
          <p class="card-text"><em><%= palace.address %></em></p>
          <%= link_to "See my palace", palace_path(palace), class:"button-card"%>
        </div>
      </div>
          <% end %>
    </div>
      </div>
</div>

app/views/pages/profil.html.erb
<div class="container mt-4">
  <h3>Informations de l'utilisateur</h3>

  <p><strong>Prénom :</strong> <%= @user.first_name %></p>
  <p><strong>Nom : </strong><%= @user.last_name %></p>
  <p><strong>Email : </strong><%= @user.email %></p>
  <p><strong>Mot de passe : </strong> **********</p>

  <%= link_to "Edit my account",  edit_user_registration_path, class: "button-primary" %>
</div>

app/views/palaces/_marker.html.erb
<%= image_tag "AirbPalace_arrow.png", height: 30, width: 30, alt: "Logo" %>

app/views/palaces/new.html.erb
<div class="container mt-5">
  <div class= "row">
    <ul class="nav nav-tabs" >
      <div class= "col-4">
        <li class="nav-item flex-fill">
          <%= link_to dashboard_palaces_path, class: "nav-link w-100" do %>
              <div aria-current="page">SEE MY PALACES</div>
          <% end %>
        </li>
        </div>
        <div class = "col-4">
        <li class="nav-item flex-fill">
          <%= link_to dashboard_bookings_as_owner_path, class: "nav-link w-100" do %>
              <div aria-current="page", >MANAGE THE BOOKING</div>
          <% end %>
          </li>
          </div>
          <div class= "col-4">
        <li class="nav-item flex-fill">
          <%= link_to new_palace_path, class: "nav-link active w-100" do %>
          <div aria-current="page", >ADD A PALACE</div>
        <% end %>
        </li>
      </div>
    </ul>
  </div>
</div>

<div class="container mt-5 d-flex justify-content-center">
  <div class = "card border-0 rounded shadow-lg p-4" style="max-width: 700px; width: 100%;">
    <%= simple_form_for(@palace) do |f| %>
    <div class="form-group mb-3">
      <%= f.input :name, label: "Name" %>
    </div>

    <div class="form-group mb-3">
      <%= f.input :description, label: "Description" %>
    </div>

    <div class="form-group mb-3">
      <%= f.input :address, label: "Address" %>
    </div>

    <div class="form-group mb-3">
      <%= f.input :price, label: "Your Price" %>
    </div>
    
    <div class="form-group mb-3">
      <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Your Photos" %>
    </div>


      <%= f.submit "Submit", class: "button-card" %>
    </div>

    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon flex-column p-3 sticky-navbar">

    <div class="navbar-top w-100 d-flex justify-content-between align-items-start">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "AirbPalace.png" %>
      <% end %>

      <div class="middle-div p-2">

        <%= link_to "", root_path, class: "mx-3"%>
        <%= link_to "MY PALACES", dashboard_palaces_path, class: "mx-3"%> |
        <%= link_to "MY BOOKINGS", dashboard_bookings_as_visitor_path, class: "mx-3"%>

      </div>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
                <% else %>

                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Profil", dashboard_profil_path , class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link custom-btn" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <!-- Partie basse -->


</div>